name: 'Notion x GitHub Action'
description: 'Sync GitHub issues to a Notion database'
inputs:
  notion-token:
    description: 'Your Notion API Token'
    required: true
  notion-db:
    description: 'The Notion database id'
    required: true
  github-org:
    description: 'Your Github org name or Github username associated with your repo'
    required: false
  github-repo:
    description: 'Your Github repo name'
    required: false
  github-token:
    description: 'Your Github personal access token'
    required: false

runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: zap
  color: gray-dark
